mysql:
  host: mysql_master
  port: 3306
  user: root
  password:
  connect_retry: 15 # seconds

tarantool:
  host: 127.0.0.1:3301
  binlog_pos_space: 512
  binlog_pos_key: 0
  connect_retry: 15 # seconds
  sync_retry: 1000 # milliseconds
mappings:
  - database: app
    table: users
    columns: [ id, email, password, firstname, lastname, birthday, sex, interests, city ]
    space: 513
    key_fields:  [ 0 ]
    # insert_call: function_name
    # update_call: function_name
    # delete_call: function_name