apiVersion: apps/v1
kind: Deployment
metadata:
  name: chats-api-deployment
spec:
  selector:
    matchLabels:
      app: chats-api
  replicas: 2
  template:
    metadata:
      labels:
        app: chats-api
    spec:
      containers:
        - name: chats-api
          image: ravilushqa/highload-chats-api
          imagePullPolicy: Always
          ports:
            - containerPort: 50051
          env:
            - name: DATABASE_URL
              value: secret
            - name: MESSAGES_SHARDS
              value: secret
            - name: REDIS_URL
              value: secret

