apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api-deployment
spec:
  selector:
    matchLabels:
      app: users-api
  replicas: 1
  template:
    metadata:
      labels:
        app: users-api
    spec:
      containers:
        - name: users-api
          image: ravilushqa/highload-users-api
          imagePullPolicy: Always
          ports:
            - containerPort: 50051
          env:
            - name: DATABASE_URL
              value: secret