apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  selector:
    matchLabels:
      app: web
  replicas: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: ravilushqa/highload-web
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: USERS_URL
              value: users-api-service:50051
            - name: CHATS_URL
              value: chats-api-service:50051