// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: services/counters/api/grpc/api.proto

package grpc

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type UnreadMessagesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *UnreadMessagesRequest) Reset() {
	*x = UnreadMessagesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_counters_api_grpc_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnreadMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnreadMessagesRequest) ProtoMessage() {}

func (x *UnreadMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_counters_api_grpc_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnreadMessagesRequest.ProtoReflect.Descriptor instead.
func (*UnreadMessagesRequest) Descriptor() ([]byte, []int) {
	return file_services_counters_api_grpc_api_proto_rawDescGZIP(), []int{0}
}

func (x *UnreadMessagesRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UnreadMessagesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int64 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *UnreadMessagesResponse) Reset() {
	*x = UnreadMessagesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_counters_api_grpc_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnreadMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnreadMessagesResponse) ProtoMessage() {}

func (x *UnreadMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_counters_api_grpc_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnreadMessagesResponse.ProtoReflect.Descriptor instead.
func (*UnreadMessagesResponse) Descriptor() ([]byte, []int) {
	return file_services_counters_api_grpc_api_proto_rawDescGZIP(), []int{1}
}

func (x *UnreadMessagesResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_services_counters_api_grpc_api_proto protoreflect.FileDescriptor

var file_services_counters_api_grpc_api_proto_rawDesc = []byte{
	0x0a, 0x24, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x65, 0x72, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x61, 0x70, 0x69,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x73,
	0x22, 0x30, 0x0a, 0x15, 0x55, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x22, 0x2e, 0x0a, 0x16, 0x55, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x32, 0x5f, 0x0a, 0x08, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x12, 0x53,
	0x0a, 0x0e, 0x55, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x12, 0x1f, 0x2e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x2e, 0x55, 0x6e, 0x72, 0x65,
	0x61, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x20, 0x2e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x2e, 0x55, 0x6e, 0x72,
	0x65, 0x61, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x1c, 0x5a, 0x1a, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x70,
	0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_services_counters_api_grpc_api_proto_rawDescOnce sync.Once
	file_services_counters_api_grpc_api_proto_rawDescData = file_services_counters_api_grpc_api_proto_rawDesc
)

func file_services_counters_api_grpc_api_proto_rawDescGZIP() []byte {
	file_services_counters_api_grpc_api_proto_rawDescOnce.Do(func() {
		file_services_counters_api_grpc_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_counters_api_grpc_api_proto_rawDescData)
	})
	return file_services_counters_api_grpc_api_proto_rawDescData
}

var file_services_counters_api_grpc_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_services_counters_api_grpc_api_proto_goTypes = []interface{}{
	(*UnreadMessagesRequest)(nil),  // 0: counters.UnreadMessagesRequest
	(*UnreadMessagesResponse)(nil), // 1: counters.UnreadMessagesResponse
}
var file_services_counters_api_grpc_api_proto_depIdxs = []int32{
	0, // 0: counters.Counters.UnreadMessages:input_type -> counters.UnreadMessagesRequest
	1, // 1: counters.Counters.UnreadMessages:output_type -> counters.UnreadMessagesResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_services_counters_api_grpc_api_proto_init() }
func file_services_counters_api_grpc_api_proto_init() {
	if File_services_counters_api_grpc_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_services_counters_api_grpc_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnreadMessagesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_counters_api_grpc_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnreadMessagesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_counters_api_grpc_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_counters_api_grpc_api_proto_goTypes,
		DependencyIndexes: file_services_counters_api_grpc_api_proto_depIdxs,
		MessageInfos:      file_services_counters_api_grpc_api_proto_msgTypes,
	}.Build()
	File_services_counters_api_grpc_api_proto = out.File
	file_services_counters_api_grpc_api_proto_rawDesc = nil
	file_services_counters_api_grpc_api_proto_goTypes = nil
	file_services_counters_api_grpc_api_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CountersClient is the client API for Counters service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CountersClient interface {
	UnreadMessages(ctx context.Context, in *UnreadMessagesRequest, opts ...grpc.CallOption) (*UnreadMessagesResponse, error)
}

type countersClient struct {
	cc grpc.ClientConnInterface
}

func NewCountersClient(cc grpc.ClientConnInterface) CountersClient {
	return &countersClient{cc}
}

func (c *countersClient) UnreadMessages(ctx context.Context, in *UnreadMessagesRequest, opts ...grpc.CallOption) (*UnreadMessagesResponse, error) {
	out := new(UnreadMessagesResponse)
	err := c.cc.Invoke(ctx, "/counters.Counters/UnreadMessages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CountersServer is the server API for Counters service.
type CountersServer interface {
	UnreadMessages(context.Context, *UnreadMessagesRequest) (*UnreadMessagesResponse, error)
}

// UnimplementedCountersServer can be embedded to have forward compatible implementations.
type UnimplementedCountersServer struct {
}

func (*UnimplementedCountersServer) UnreadMessages(context.Context, *UnreadMessagesRequest) (*UnreadMessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnreadMessages not implemented")
}

func RegisterCountersServer(s *grpc.Server, srv CountersServer) {
	s.RegisterService(&_Counters_serviceDesc, srv)
}

func _Counters_UnreadMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnreadMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CountersServer).UnreadMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/counters.Counters/UnreadMessages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CountersServer).UnreadMessages(ctx, req.(*UnreadMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Counters_serviceDesc = grpc.ServiceDesc{
	ServiceName: "counters.Counters",
	HandlerType: (*CountersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UnreadMessages",
			Handler:    _Counters_UnreadMessages_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/counters/api/grpc/api.proto",
}
